### ISSUE TITLE
To help users leave better feedback: consider language edits to feedback tool

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-style#173]
#### Current content
<img width="541" alt="screen shot 2015-11-05 at 11 17 10 am" src="https://cloud.githubusercontent.com/assets/10552702/10974187/d410e3b4-83ae-11e5-8958-f8bfbc6a832a.png">

#### Tasks to completion:
 - [ ] Draft preloaded text (if we want)
 - [ ] Propose edits to feedback prompts
 - [ ] Finalize all content   
 - [ ] Implement @emileighoutlaw

**Comment by jenniferthibault** [comment]
I would love to create more clear distinction between the first and second questions (What were you doing?/What happened?) Seems like now these are a bit redundant, and the pattern of feedback we've been receiving seems to show that users aren't really separating the fields in a meaningful way.

What if....something along these lines?

**Tell us about what you were trying to do**
*I am a ______ interested in ______. I was trying to....*

**What could be improved or corrected about that task?**

**Or, just give us some feedback** or **General feedback**


OR!


**Tell us about yourself**
*I am a ______ interested in ______.* 

**Tell us about what you were trying to do on the site, and how it could be improved**

**Or, just give us some feedback** or **General feedback**

**Comment by emileighoutlaw** [comment]
Great draft, Jen! Here's my thinking:

I like adding a note at the top that every field is optional. From there, it seems there are three pieces of info we'd like.

1. Who the person is
2. What they were doing/what went wrong
3. General feedback

For 2. to be complete we need to know both what they were doing and what went wrong. So it seems wise to keep them as one field. People either fill it out, or they leave general feedback.

As a jumping off point:

1.
>**Help us improve betaFEC**
>*All fields are optional. Don't include sensitive information...*

>Tell us about yourself
>*I'm a ______ interested in ________.*

> What were you trying to do, and how can we improve it?

> General feedback

2.
>**Help us improve betaFEC**
>*All fields are optional. Don't include sensitive information...*

>Tell us about yourself
>*I'm a ______ interested in ________.*

> How can we improve your experience?
> *I was trying do ___________ when _________ happened.*

> General feedback



We could also make the "Tell us about yourself" the last field, since it's a nice thing to have but not critical.

**Comment by noahmanger** [comment]
I like this idea! I'm fine with either construction, and I think I like the idea of having the "I'm a ___" question last.

As for how the hints are supposed to be, should we show them as hint text underneath the field label? Or as placeholder text? Or actually pre-populate the text in the field and people can edit it? 

Probably best not to just do placeholder text, as it disappears as soon as someone starts typing.

**Comment by emileighoutlaw** [comment]
I think either placeholder text or pre-populated. If you think placeholder isn't a good option, @noahmanger, then my vote is for pre-populated text. Curious to hear what @jenniferthibault thinks. :)

**Comment by jenniferthibault** [comment]
I'm in favor of @emileighoutlaw 's text option 1 because I think it's a good point that we don't want to guide the "problem" they're coming in with too much through our language. Also like the idea of moving the bit about themselves to the end, since that's something WE're more interested in than they are, so don't want to give it more priority that the feedback itself.

On where the hint text goes, I'm inclined to remove it from the box itself so that it's always there, but not too strict that users HAVE to follow the format.

All that combined could look like this:
<img width="480" alt="screen shot 2015-11-12 at 10 01 42 am" src="https://cloud.githubusercontent.com/assets/11636908/11126751/48d812be-8925-11e5-8651-1d1dfb558cbc.png">

**Comment by emileighoutlaw** [comment]
Oh, i think that looks great @jenniferthibault !

**Comment by noahmanger** [comment]
I like it!

On Thu, Nov 12, 2015 at 10:47 AM, Emileigh Barnes <notifications@github.com>
wrote:

> Oh, i think that looks great @jenniferthibault
> <https://github.com/jenniferthibault> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fec-style/issues/173#issuecomment-156198511>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by emileighoutlaw** [comment]
Also, when we go in and change it, Social Security should be capitalized!
