### ISSUE TITLE
In order to ensure visual consistency & good design, perform a visual audit of registration and reporting side

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#176]
Story map card: [Candidate committees can find out how to register](https://18f.storiesonboard.com/m/fec/!card/4sHk8_8fF-AnQTnTwqtsBA)

**Comment by jenniferthibault** [comment]
I used the registration and reporting pages in a "cold start" critique session with a few folks from 18F — what I mean by cold start is that they hadn't seen the page designs, wireframes, or content up until this point, and they were coming in with completely fresh perspectives that were immensely helpful. Some thoughts from their reviews below, but I'll also outline changes that are strictly visual, or came from comparing the original designs from what was actually implemented in a second comment. There was often a good deal of variance in both structure and layout, which is worth discussing what was intentional and what wasn't.

## Critique group feedback:
 -The information architecture feels burdensome, and at times, vaguely guided. Could possibly benefit from knowing user flows better. The hero section is a good case of this as an opportunity to demonstrate what exists in this portion of the site:
<img width="1177" alt="screen shot 2015-11-12 at 12 21 37 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130096/05a28f34-8938-11e5-9abd-b712354d4d9c.png">
 -Confusion about why there are two different buttons on the landing page that go to the same place.
<img width="425" alt="screen shot 2015-11-12 at 12 23 08 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130116/2ed1a3ae-8938-11e5-9650-cffea9d1aca1.png">
<img width="357" alt="screen shot 2015-11-12 at 12 23 13 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130117/2ed7414c-8938-11e5-97b0-bf4c757371a0.png">  
 - Strong suggestion to make the button text and headlines more specific, felt strongly that "discover" and "explore" are too vague. cc @emileighoutlaw  - this tracks us way way back to this discussion https://github.com/18F/fec-cms/issues/19#issuecomment-142363805
 - Suggestion to split the actions and user pathways more clearly into "Registration" (which is something you do once? and "Reporting" which is something that happens continuously. Possibly use the hero area to reinforce this.
  - This would likely mean a significant change the architecture of the current content and part of the site, I think we would want to hear this feedback directly from users before making this level of change.
 - Can we give users better access to the essentials pages directly from the landing page? Feels like many clicks to get there ultimately
 - Does the "checklist" really need to be an accordion? Suggested to check out USCIS work for examples
 - Desired ability for users to be able to click from one sub-task to another without needing to go back to the whole checklist. Possibly "Next/Previous steps" buttons

cc // @onezerojeremy @noahmanger @emileighoutlaw 
## Tasks based on my design evaluation

**Comment by jenniferthibault** [comment]
## Tasks based on my design evaluation
Some of these may need to be drawn out into separate issues for discussion, but I wanted to keep a catalog of changes from this review together. If new unique issues are created, please (everyone, anyone) edit this to include the link by each point.

### Overall changes
 - [ ] Change body copy to 1rem = 16pt throughout the site. This will help in cases where character count per line is currently too large for ideal readability but also...
 - [ ] Limit paragraph text to 3/4 columns wide at max:
This
<img width="1279" alt="screen shot 2015-11-12 at 12 51 41 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130868/479b09a8-893c-11e5-9150-fdd05e7ac837.png">
instead of this:
<img width="1280" alt="screen shot 2015-11-12 at 12 52 53 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130878/554fef3c-893c-11e5-8a8c-27234affa996.png">

### Essentials:
<img width="1279" alt="screen shot 2015-11-12 at 1 05 10 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131164/18c52f4e-893e-11e5-9cf3-764a4590a773.png">
 - [ ] Remove top rule line from H1's 
 - [ ] Increase space between bottom of H1 rule and body copy
 - [ ] Put at least 1 column of space between edge of body copy content and resources panel on the right
 - [ ] Increase space between bottom H1 rule line and top of resources box
 - [ ] Originally, this was our design for the resources panel: why did we move away from this, and do we want to bring this back as "Coming soon" content? cc @noahmanger 
<img width="238" alt="screen shot 2015-11-12 at 1 14 57 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131401/7b69de5a-893f-11e5-96c6-0212f3e570c6.png">
 - [ ] Consider removing accordion functionality in favor of lists that are shorter than most users might assume. The content is surprisingly short!
 - [ ] Change checkboxes to bullets
<img width="265" alt="screen shot 2015-11-12 at 1 19 08 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131537/fa7c9c5a-893f-11e5-9e3d-1d32f5d2287f.png">
 - [ ] Add link and `PDF` to campaign guide to match original design.
<img width="327" alt="screen shot 2015-11-12 at 1 20 02 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131580/3780f5d8-8940-11e5-9c5e-3d957bbbe559.png">
 - [ ] Another place we deviated from the design was having the "Need help?" as an element at the end of the page, but above the footer. Do we want to bring this back, complete with "Coming soon" content elements? cc @noahmanger 
<img width="851" alt="screen shot 2015-11-12 at 1 22 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131675/abc326c8-8940-11e5-9bce-d60203ed9502.png">

### Individual articles/pages:
<img width="1278" alt="screen shot 2015-11-12 at 1 26 41 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131757/196b8652-8941-11e5-8187-6095957b4461.png">
 - [ ] Remove top rule line from H1's 
 - [ ] Reconsider title line-length caps
 - [ ] Same spacing changes between content and resources box as Essentials pages


....to be continued with updates

**Comment by emileighoutlaw** [comment]
Ahhhhh yes. That damn button and headline copy. I totally agree that it's vague and that the vagueness is an issue. I'll open an issue for that.

I do feel torn about the accordion on the essentials page. I have seen users in usability sessions miss a section of content because it wasn't under the header they expected, and they didn't click to expand the others.

**Comment by jenniferthibault** [comment]
For discussion and preferences! cc @emileighoutlaw @noahmanger @onezerojeremy 

## Low-design-polish options for alternative formats for the Essentials page:

### Option 1: Freedom from accordions!

![checklist](https://cloud.githubusercontent.com/assets/11636908/11252957/f015f844-8e06-11e5-8420-fac7cd144077.png)

##### Notes:
- This allows users to see that the information contained in each list is actually rather short and approachable.
- Creates a shorter page on the whole

_____

### Option 2: Fewer pages, filtered categories, and a different type of accordion!
![checklist copy 3](https://cloud.githubusercontent.com/assets/11636908/11252993/119237e4-8e07-11e5-880a-456cf5daa9f5.png)

#### Filtered and expanded:

![checklist copy 4](https://cloud.githubusercontent.com/assets/11636908/11253006/25922f4c-8e07-11e5-8c08-9747d7751d59.png)


##### Notes:
- Based heavily on this pattern from myUSCIS, which I'm sure has lots of testing around. We could find out from that 18F project team what the risks/benefits they've experienced with their users of this type of layout are.
- We'd still need individual article pages like [this](https://beta.fec.gov/registration-and-reporting/house-and-senate-candidate-committee-registration/) to link to from "More details," which I think is a good level of separation.
- I’m interested in this direction because it feels like we’re cutting down on page sprawl, and it lets you see multiple steps and needs at the same time. 
- One potential downside is that the steps feel less linear. 
- @emileighoutlaw I'm not sold on this language I just made up for this, but I think you get the general need. Feel free to ignore if we don't pursue this route.  
![screen shot 2015-11-18 at 3 22 12 pm](https://cloud.githubusercontent.com/assets/11636908/11253220/3216bc00-8e08-11e5-8d6d-6c8db9a93f16.png)

**Comment by jenniferthibault** [comment]
Ok ok, last from me on this until I hear more from you all, BUT here's what this second option could look like with imagery (images not precise or final, I definitely gave up on `troubleshooting` for now): 

![checklist copy 3a](https://cloud.githubusercontent.com/assets/11636908/11278843/366d4658-8ebb-11e5-8ff3-8d3feea5b292.png)

**Comment by emileighoutlaw** [comment]
This is amazing work.

I am particularly struck by the visual design in the myUSCIS-inspired ones. The only thing I think feels missing in those is the easily distinguishable sectioning of the first. 

The first option isn't as lovely, but it's got four manageable sections. As a reader, it's easy for me to chunk the content and identify what I need to do. By comparison, the next two feel more overwhelming in terms of tasks to complete and identifying where I am in the FEC lifecycle. I wonder if there's a way to alleviate that feeling at all?

**Comment by noahmanger** [comment]
Yeah, I think I'm with Emileigh. _Thinking as I type:_

I'm all for removing accordions. Seems like they're not helping, and in some cases hurting. So yay!

But I think the value of the checklist page is in presenting content in a linear, "chunk-able" way so that users have a clear path of everything they need to do in order to accomplish a particular goal.

In this case, the needs of this page are very different than the needs that the USCIS-type interaction is designed for, which seems to me to be one of "identify a goal, get a list of various parallel routes to that goal", rather than "identify a goal, get a list of synchronous steps to accomplish that goal".

But / and: I could potentially see value in this tile-type interface elsewhere in the site. For example, we've talked about but never designed an alternate view to all of the articles, one where they're not segregated by audience, but where they're all visible, browsable and searchable. Maybe this would be part of that view?

**Comment by jenniferthibault** [comment]
Thank you both! I was definitely also feeling the loss of order to the content in that second format. The USCIS pattern felt like a close cousin to what we needed, and I found it really helpful to explore that direction just to clear up many of these points. What I'm hearing from you and seeing on these pages is:
- removing the first tier of accordions feels helpful, and makes the steps more apparent
- keeping strict groups and categories that doesn't require a first step on the users' side is the ideal starting point
- being able to see what step comes before and after the step you're on is a helpful experience (i can think of a few design approaches to this)
- this tile-type interface might be helpful in a larger library of information

**Comment by noahmanger** [comment]
I think that's right on. The other thing I remembered about why we designed the checklist as a linear list: it was also to give people an understanding of all of the responsibilities and things that they'll have in the future to help them decide if this is really the right thing for them.

The hypothesis being that someone who comes to register can see what happens down the road and that will help them make the right decision about whether or not they should.

**Comment by jenniferthibault** [comment]
Been working on this a lot, and think I have something that gets closer to the bullets above. It uses the pattern in the works on the Registration & Reporting home page here https://github.com/18F/fec-style/issues/180#issuecomment-159027799, so if we find flaws with it there, that would carry over.

## Option 1: Mini accordions for article pages

### Landing stage:
![checklist copy 7a](https://cloud.githubusercontent.com/assets/11636908/11353705/831ab49e-9213-11e5-92aa-3ec58869ffaf.png)

### Interaction:
Each list item would be an accordion with the content for that element in line. In cases where the [content is long](https://beta.fec.gov/registration-and-reporting/get-treasurer/) or links to more explanation like this [base copy](https://beta.fec.gov/registration-and-reporting/register-now/) and [where it links to](https://beta.fec.gov/registration-and-reporting/house-and-senate-candidate-registration/), this could be the introductory clip, and the full version could be on an independent page.  

![checklist copy 6](https://cloud.githubusercontent.com/assets/11636908/11354075/b813a54a-9216-11e5-95b1-13298a8ec91f.png)
 


Independent pages should add previous/next article link, and a "back to essentials" link to help users remain oriented with where they are in the list. I've added it here, not 100% positive on the placement though. Language check, @emileighoutlaw ?  

![knowledge center item](https://cloud.githubusercontent.com/assets/11636908/11353959/ef76e35e-9215-11e5-8e0b-b0355af87e8f.png)

## Option 2: Back to bullets
In the event that we don't like this accordion interaction on each article, we COULD use the plain bullet format, which would then link to the individual article pages again. This would use the same previous/next designs as the first option

![checklist copy 7](https://cloud.githubusercontent.com/assets/11636908/11353974/1ca0d4f2-9216-11e5-9217-9fe5d2504e3e.png)

**Comment by jenniferthibault** [comment]
I also realize that I've been SUPER in the weeds with this page and the registration home page. If it's easier to talk through things by voice, let's do that :)

**Comment by emileighoutlaw** [comment]
I'm really excited by this work. I found Option 1 intuitive and easy to use— I think you're spot on with all the new link copy.

Really enjoyed the "Previous article" and "Next article" construction. I think it'll be a really nice functionality for folks who start reading and want to keep moving through the steps without clicking back and forth to the essentials page. Questions about the callout pages:
- What happens when the previous or next article is short, like "Get a bank account," and doesn't have a "More details" link on the main essentials page. Will there be an independent page for everything, even if it isn't linked on the callout?
- I think we might want to somehow call more attention to the "Back to essentials" link? Maybe some sort of ↩or similar, so it looks equally like a link with movement.

Happy to jump on a call to discuss if it's helpful. This is awesome.

**Comment by jenniferthibault** [comment]
Excellent questions! I would love your & @noahmanger 's help thinking through the first, specifically. 

I was wondering if (/hoping) an open accordion panel could create a unique URL so that folks could still share specific articles. If that's the case, then I was thinking very short articles wouldn't need individual pages, and a next/previous that goes to a short article could link back to the essentials page with that panel open. But maybe that's jarring, and we'd want every article to have it's own page anyway.

Wondering if you two might have thoughts on other solutions. Just set up a quick chat for us this afternoon!

**Comment by jenniferthibault** [comment]
Final designs & implementation moved to #193 and #194
