### ISSUE TITLE
Update styleguide with new components

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#212]
**[Story](https://18f.storiesonboard.com/m/fec/!card/dSDD9jsDpx8iGTnTwnAhdQ):** So that the team can design with confidence and consistency, audit and update the styleguide to make sure it encompasses and accurately reflects our patterns.

**Tasks:**
- [x] ~~Add markup for all partials~~ => See below
- [x] Add colors
- [x] ~~Audit for consistency~~ => Make new issues for visual and code consistency updates

**Add or update the following components:**
- [ ] ~~Calendar components~~ (move to modules)
- [ ] ~~Charts~~ (deferring to later)
- [x] Contact items
- [x] Cycle select
- [x] Downloads
- [x] Dropdowns
- [x] Icon headings
- [ ] ~~Maps~~ (deferring to later)
- [x] Options
- [x] Overlay
- [x] Search results
- [x] Side nav
- [x] Table styles

**Comment by noahmanger** [comment]
Colors! 
![screen shot 2016-02-04 at 5 43 09 pm](https://cloud.githubusercontent.com/assets/1696495/12835701/587792ba-cb67-11e5-91b7-787117bbf56c.png)
